### PR TITLE
Adding podAnnotations for tests #50

### PR DESCRIPTION
**Pull request by anthosz**
_Descriptive description goes here._

Tasks:

- [x] I've made changes
- [x] I've bumped chart's version in `Chart.yaml`
- [x] I've added changes to charts `CHANGELOG.md`
- [x] I've run [`helm-docs`](https://github.com/norwoodj/helm-docs)
- [ ] I've run ['helm-tool schema | jq . > values.schema.json'](https://github.com/cert-manager/helm-tool)

### CODE REVIEW

**Comment by anthosz** [comment]
Related to #50

**Comment by MaikuMori** [comment]
I think this doesn't necessarily do what you want. If it's the same annotation, and you ignore checks for test pod, you're now also ignoring checks on Gotenberg pod which maybe are valuable.

So I see 2 options:

 - Add separate values entry
 - Add `kube-score` annotations to test pod in the chart itself.

I think the 1st option is more universal.

**Comment by MaikuMori** [comment]
Combined with #49

**Comment by anthosz** [comment]
Thank you @MaikuMori !

**Pull request closed without merging**
