### PR TITLE
Add tmp volume

### PR DESCRIPTION
**Pull request by pschumacher**
The Chromium module needs to be able to write to the /tmp directory of the container. When running the container with a read-only filesystem (securityContext.readOnlyRootFilesystem), this leads to the following Gotenberg error:

`create request context: create working directory: create directory /tmp/6035cd1c-8e13-4e53-a871-c4c56d3e04bc: mkdir /tmp/6035cd1c-8e13-4e53-a871-c4c56d3e04bc: read-only file system`

In oder to support running a read-only filesystem, it should be possible to configure a volume that is mounted at /tmp.

Tasks:

 - [ x ] I've made changes
 - [ x ] I've bumped chart's version in `Chart.yaml`
 - [ x ] I've added changes to charts `CHANGELOG.md`
 - [ x ] I've run [`helm-docs`](https://github.com/norwoodj/helm-docs)

### CODE REVIEW

**Comment by MaikuMori** [comment]
Hi, I'll review this shortly. Overall looks ok.

**Comment by MaikuMori** [comment]
My only concern is the default volume.

This is because now by default we're allocating up to 2Gb extra memory on the node.  I would prefer to just comment the default volume out and leave it as an example for whomever needs it as a template.

An alternative would be to place it behind a flag.

What do you think?

**Comment by pschumacher** [comment]
Sounds good. I have commented the default volume out and added the option to define volumeMounts.

**Comment by MaikuMori** [comment]
Thanks for the PR. I think read-only rootfs is definitely the way to go.  Maybe it should be supported more explicitly among other hardening settings in the future.

**Pull request merged**
